server:
  port: 81

spring:
  application:
    name: cloud-order-service

  devtools:
    livereload:
      port: 35730


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka